### PR TITLE
Macaulay2 1.17 (new formula)

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mahrud** [comment]
@carlocab do you have any suggestions for getting the build logs? I tried using upload artifact:
https://github.com/mahrud/homebrew-tap/blob/91382c9121c75c2d82e85bab7304c6ad269dd920/.github/workflows/tests.yml#L51-L54
but the temp directories are cleaned before that step. Is there any way to keep them?

This formula is the main formula that I need, everything else has been dependencies. I'm having some linkage issues on ubuntu because some are compiled with gcc-5 and don't behave well with the newer c++ abi. Any suggestions for that? Currently I'm adding this block to all of my formulae:
https://github.com/mahrud/homebrew-tap/blob/91382c9121c75c2d82e85bab7304c6ad269dd920/Formula/macaulay2.rb#L14-L18

**Comment by carlocab** [comment]
I haven't managed to get useful logs out of GitHub runners as of yet, but how it's done on homebrew/core may be informative:

https://github.com/Homebrew/homebrew-core/blob/adc321765ad52895ccfffd95747e3755bc53a03a/.github/workflows/tests.yml#L119-L130

As for specifying your compiler, doesn't the flag `-DCMAKE_C{XX}_COMPILER` work? This discussion might also help: https://github.com/Homebrew/brew/issues/10170 It seems the default compiler is always the newest `gcc` available to the build environment?

**Comment by mahrud** [comment]
I see, okay. I was hoping that the `--keep-tmp` option of brew install could be somehow passed to test bot.

**Comment by carlocab** [comment]
I see you got this to build. Nice!

**Comment by mahrud** [comment]
Yes, took a whole week! Thank you so much for all the help!

**Pull request closed without merging**
