### PR TITLE
patch csdp

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mahrud** [comment]
@carlocab do you have any suggestions for how to figure out what is going wrong in this PR?

Here is what happened:
- in #14 I added a formula for csdp
- in order to get it to compile I had to add a patch
- test-bot did not like a patch in a new formula and interrupted the build
- no bottle for the macOS build was created
- I added `pr-pull` to merge it anyway

I was hoping that when I make a revision it will ignore the patch and build bottles for both ubuntu and macos, but that doesn't seem to be happening. I thought deleting the generated release would help, but that didn't work either. I tried manually erasing the bottles from the formula, but that doesn't seem to have worked either.

I understand that not having patches in new formulae is preferred, but I wish there was a way to disable that.

**Comment by carlocab** [comment]
Yea, test-bot doesn't like unfamiliar formulae with patches. Cf. https://github.com/Homebrew/brew/issues/10216

This should be fixed at some point. In the meantime, you can trick test-bot into thinking it's not a new formula by merging some version of it into your master branch for now. Then, make a modification and open a PR for that modification. Things should work for you from there.

**Comment by mahrud** [comment]
That's basically what I did, and this is the second PR that I was hoping would fix it.
Is there any way I could force the actions log to be verbose? Currently it's hiding everything, and at the end failing with this error:
```
==> brew audit mahrud/tap/csdp --online --git --skip-style
==> FAILED
mahrud/tap/csdp:
  * The installation seems to be empty. Please ensure the prefix
    is set correctly and expected files are installed.
    The prefix configure/make argument may be case-sensitive.
Error: The installation seems to be empty. Please ensure the prefix
is set correctly and expected files are installed.
The prefix configure/make argument may be case-sensitive.

Error: 1 problem in 1 formula detected
```

**Comment by carlocab** [comment]
Weird. That means nothing's being installed in `#{prefix}` for some reason. I think you should be able to activate verbose output by setting the environment variable `HOMEBREW_VERBOSE`. Any non-empty value will do. If that still doesn't give you anything useful, try `HOMEBREW_DEBUG` too.

**Comment by mahrud** [comment]
I set both to "on" inside the install block of the formula but the github actions log is the same. I presume you meant set the env locally? Unfortunately I don't have access to a mac, and on linux it's working fine! Is there a way to get github actions to be verbose?

**Comment by carlocab** [comment]
Yes, I don't think `brew` reads the environment variables you set in the formula file. Even if it does, it's too late by then.

You'll need to set it here: https://github.com/mahrud/homebrew-tap/blob/main/.github/workflows/tests.yml

**Comment by mahrud** [comment]
Ahh, I see. I'll try that. Thanks!

**Comment by carlocab** [comment]
Otherwise, you could try adding a `--verbose` flag here:

https://github.com/mahrud/homebrew-tap/blob/d13d0ae5b631778a0ce7d59a7ffa81daec1f9814/.github/workflows/tests.yml#L35

**Comment by carlocab** [comment]
Another tip: set `fail-fast: false` so that failures on one runner don't kill tests on the other.

See https://github.com/carlocab/homebrew-personal/blob/95ca5ab0037ec7412b816eea62c1e5bafe23f6e4/.github/workflows/tests.yml#L6-L11

**Comment by mahrud** [comment]
Lol turns out there's an `INSTALL` file in the same directory which confuses make, but only on macOS! Thanks a lot for the tips!

**Pull request closed without merging**
